version: '3.7'

services:
  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla
    command: --developer-mode=1 --smp 1
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 180s # wait for scylla to start
          
  manatrends:
    image: evilgenius13/manatrends:latest
    container_name: manatrends
    depends_on:
      - scylla
    ports:
      - "9292:9292"
    environment:
      - STEAM_API_KEY=${STEAM_API_KEY}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


 
volumes:
  scylla_data: