steps:
  - label: ":hammer: Build and Push"
    command: "scripts/build-and-push.sh"

  - wait

  - label: ":rocket: Deploy"
  # Kubernetes deployment to be replaced here
    command: "echo 'Add deployment script here'"
  
  - wait

  - label: ":large_green_circle: Notify on Success"
    command: "notify-discord-success.sh"
    if: build.state == "passed"
    env:
      DISCORD_WEBHOOK_URL: "$DISCORD_WEBHOOK_URL"

  - label: ":large_orange_circle: Notify on Failure"
    command: "notify-discord-failure.sh"
    if: build.state == "failed"
    env:
      DISCORD_WEBHOOK_URL: "$DISCORD_WEBHOOK_URL"